# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
      
      echo "1" | java -jar "C:\Users\wesley.nutley\Downloads\ready-api-license-manager\ready-api-license-manager\ready-api-license-manager-1.2.6.jar" -s SB-MA-PC0BXUDC:1099'
    errorActionPreference: 'continue'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
