/**
 * My-Petstore MINIMAL OpenAPI2.0
 * MANUALLY-SLASHED sample-API
 *
 * OpenAPI spec version: 1.0.0-OpenAPI2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Returns a single pet
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   *   code 400 :  (Invalid ID supplied)
   *   code 404 :  (Pet not found)
   *   code 405 :  (Validation exception)
   *   code 500 :  (Internal Error while processing API request)
   */
  def getPetById(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost/playground", "/pet", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](404)
      .withErrorResponse[Unit](405)
      .withErrorResponse[Unit](500)
      

}

